### ISSUE TITLE
Weblate not working anymore

### ISSUE THREAD

**Issue by mscherer** [woodpecker-ci/infrastructure#11]
Seems the weblate installation of woodpecker is broken, I see a message on not being able to rebase the repo when I try to continue working on the french one. It point to that FAQ: https://docs.weblate.org/en/weblate-4.13.1/faq.html#merge

Not sure where to report, or if it was noticed already, and not sure if I have required access for that (but I doubt).

**Comment by anbraten** [comment]
Thanks for reporting. I enabled notifications for my account now to be notified each time a conflict occurs. Should be fixed for now.
