### ISSUE TITLE
Deploy centrally via WP or Semaphore

### ISSUE THREAD

**Issue by pat-s** [woodpecker-ci/infrastructure#36]
Instead of local applies

**Comment by anbraten** [comment]
I like the idea of doing less manual interaction with the server. This also helps with using review to reduce the risk of misconfiguration / deleting something. On the other hand I would absolutely like to try to keep things super simple here in a matter of failures through complexity and costs. Using wp would probably end in a chicken-egg problem at some point. Using Semaphore sounds like a good idea. However we would need to use the cloud offering (seems to be offline atm) for the same reasons again.

**Comment by pat-s** [comment]
Ideally Semaphore would/should run on a dedicated small cloud VM to be independent of the resources it provisions. However this would require a standalone VM for only Semaphore which would be an inefficient use of resources. 

Local applies are a fallback in case of inaccessability of the central deployment application. 
Yet it could also run on an existing machine as the fallback of local applies and manual ssh into the VM always exists.

**Comment by pat-s** [comment]
Doing now so via WP's ansible plugin.
