### ISSUE TITLE
Go vanity urls for woodpecker

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/infrastructure#4]
```
go.woodpecker.org {
	root * /var/www/html
	file_server

	route /woodpecker {
		@goget query go-get=1
		respond @goget `<meta name="go-import" content="go.woodpecker.org/woodpecker git https://github.com/woodpecker-ci/woodpecker">`

		redir https://pkg.go.dev/github.com/woodpecker-ci/woodpecker
	}
}
```

Source: https://caddy.community/t/vanity-go-import-paths-for-caddy-2/9814

**Comment by anbraten** [comment]
@6543 Could you point `go.woodpecker.org` to our vps? We should maybe thing about using a NS record at Strato to be able to use a DNS with a proper API like Hetzner, Cloudflare, so we could manage domains with ansible as well.

**Comment by anbraten** [comment]
@jolheiser What do you think about this vanity url. We would use `go.woodpecker.org/woodpecker` instead of `github.com/woodpecker-ci/woodpecker` if I understood everything right.

**Comment by 6543** [comment]
dns A record done - do we have an AAAA record to set (ipv6 address)

**Comment by anbraten** [comment]
Update: I configured `go.woodpecker-ci.org/woodpecker` to be our redirect, so we should be able to replace it in our main project now.

**Comment by jolheiser** [comment]
Sorry, I didn't see this until now. (I _hate_ GitHub notifications, I never seem to know I have new mentions)

This looks good, but keep in mind we'll need to change our `go.mod` and all references to our module as well as this change.

But overall I think it's a good idea so we don't have to deal with changing it multiple times.

**Comment by 6543** [comment]
-> https://github.com/woodpecker-ci/autoscaler/pull/48
