### ISSUE TITLE
translate.woodpecker-ci.org

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/infrastructure#5]
I would like to test a self-hosted weblate instance. For this I need a domain `translate.woodpecker.org` pointing to our server (CNAME woodpecker-ci.org).

In addition we  need an email address which we can use with weblate. Maybe we already have one we could re-use.

**Comment by anbraten** [comment]
@6543 Could you configure dns and provide me email credentials via Matrix.

**Comment by 6543** [comment]
CNAME done

**Comment by 6543** [comment]
`translate @ woodpecker-ci.org` ?

**Comment by 6543** [comment]
@anbraten can you create a pull to add it to ansible?

**Comment by 6543** [comment]
& I think we should enable Oauth2 login for github & codeberg https://docs.weblate.org/en/latest/admin/auth.html
