### ISSUE TITLE
Get dedicated woodpecker agent

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/infrastructure#6]
Instead of using the same server for Woodpecker server and agent we should get a separate server to use for the agent and downgrade our current server.

**Comment by 6543** [comment]
#9 is a step into this direction

**Comment by pat-s** [comment]
Has this been applied in the meantime?

**Comment by 6543** [comment]
No ... but i would wait for the arm issues to be solved and use arm then

**Comment by anbraten** [comment]
I actually did so in the meantime while reinstalling the server. The main woodpecker server is now the smallest arm machine just running wp-server, wp-autoscaler, weblate and caddy all installed as visible in the ansible manifest. I will create an issue with some more details tomorrow.
